package indexbg.pjobs.wsclient.stJobs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-04-10T15:15:53.151+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "https://eisuchrda.egov.bg/IISDAIntegrationServices/Common", name = "StJobs")
@XmlSeeAlso({ObjectFactory.class})
public interface StJobs {

    @WebResult(name = "GetJobsClassificationResult", targetNamespace = "https://eisuchrda.egov.bg/IISDAIntegrationServices/Common")
    @Action(input = "GetJobsClassification", output = "GetJobsClassification")
    @RequestWrapper(localName = "GetJobsClassification", targetNamespace = "https://eisuchrda.egov.bg/IISDAIntegrationServices/Common", className = "indexbg.pjobs.wsclient.stJobs.GetJobsClassification")
    @WebMethod(operationName = "GetJobsClassification", action = "GetJobsClassification")
    @ResponseWrapper(localName = "GetJobsClassificationResponse", targetNamespace = "https://eisuchrda.egov.bg/IISDAIntegrationServices/Common", className = "indexbg.pjobs.wsclient.stJobs.GetJobsClassificationResponse")
    public indexbg.pjobs.wsclient.stJobs.ArrayOfJobClassification getJobsClassification(
        @WebParam(name = "classificationCode", targetNamespace = "https://eisuchrda.egov.bg/IISDAIntegrationServices/Common")
        indexbg.pjobs.wsclient.stJobs.JobClassifierCode classificationCode
    );
}
