package indexbg.pjobs.wsclient.stJobs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-04-10T15:15:53.158+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "StJobs", 
                  wsdlLocation = "file:/d:/StJobs.wsdl",
                  targetNamespace = "https://eisuchrda.egov.bg/IISDAIntegrationServices/Common") 
public class StJobs_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://eisuchrda.egov.bg/IISDAIntegrationServices/Common", "StJobs");
    public final static QName BasicHttpBindingStJobs = new QName("https://eisuchrda.egov.bg/IISDAIntegrationServices/Common", "BasicHttpBinding_StJobs");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/StJobs.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StJobs_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/StJobs.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StJobs_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StJobs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StJobs_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StJobs_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StJobs_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StJobs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StJobs
     */
    @WebEndpoint(name = "BasicHttpBinding_StJobs")
    public StJobs getBasicHttpBindingStJobs() {
        return super.getPort(BasicHttpBindingStJobs, StJobs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StJobs
     */
    @WebEndpoint(name = "BasicHttpBinding_StJobs")
    public StJobs getBasicHttpBindingStJobs(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingStJobs, StJobs.class, features);
    }

}
