package indexbg.pjobs.wsclient.govcomp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-02-28T16:28:41.171+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebServiceClient(name = "CompetitionService",
                  wsdlLocation = "https://iisda.government.bg/Services/Competitions/Competitions.IntegrationServices/CompetitionService/CompetitionService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class CompetitionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "CompetitionService");
    public final static QName BasicHttpBindingICompetitionService = new QName("http://tempuri.org/", "BasicHttpBinding_ICompetitionService");
    public final static QName BasicHttpsBindingICompetitionService = new QName("http://tempuri.org/", "BasicHttpsBinding_ICompetitionService");
    static {
        URL url = null;
        try {
            url = new URL("https://iisda.government.bg/Services/Competitions/Competitions.IntegrationServices/CompetitionService/CompetitionService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CompetitionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://iisda.government.bg/Services/Competitions/Competitions.IntegrationServices/CompetitionService/CompetitionService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CompetitionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CompetitionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompetitionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CompetitionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CompetitionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CompetitionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICompetitionService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICompetitionService")
    public ICompetitionService getBasicHttpBindingICompetitionService() {
        return super.getPort(BasicHttpBindingICompetitionService, ICompetitionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICompetitionService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICompetitionService")
    public ICompetitionService getBasicHttpBindingICompetitionService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingICompetitionService, ICompetitionService.class, features);
    }


    /**
     *
     * @return
     *     returns ICompetitionService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICompetitionService")
    public ICompetitionService getBasicHttpsBindingICompetitionService() {
        return super.getPort(BasicHttpsBindingICompetitionService, ICompetitionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICompetitionService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICompetitionService")
    public ICompetitionService getBasicHttpsBindingICompetitionService(WebServiceFeature... features) {
        return super.getPort(BasicHttpsBindingICompetitionService, ICompetitionService.class, features);
    }

}
