package indexbg.pjobs.wsclient.govcomp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-02-28T16:28:41.146+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices", name = "ICompetitionService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICompetitionService {

    @WebMethod(operationName = "SearchCompetitions", action = "http://iisda.government.bg/Competitons/IntegrationServices/ICompetitionService/SearchCompetitions")
    @Action(input = "http://iisda.government.bg/Competitons/IntegrationServices/ICompetitionService/SearchCompetitions", output = "http://iisda.government.bg/Competitons/IntegrationServices/ICompetitionService/SearchCompetitionsResponse")
    @RequestWrapper(localName = "SearchCompetitions", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices", className = "indexbg.pjobs.wsclient.govcomp.SearchCompetitions")
    @ResponseWrapper(localName = "SearchCompetitionsResponse", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices", className = "indexbg.pjobs.wsclient.govcomp.SearchCompetitionsResponse")
    @WebResult(name = "SearchCompetitionsResult", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
    public indexbg.pjobs.wsclient.govcomp.ArrayOfCompetitionType searchCompetitions(
        @WebParam(name = "competitonID", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
        java.lang.Long competitonID,
        @WebParam(name = "batchIdentificationNumber", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
        java.lang.String batchIdentificationNumber,
        @WebParam(name = "batchUIC", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
        java.lang.String batchUIC,
        @WebParam(name = "DateAt", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
        javax.xml.datatype.XMLGregorianCalendar dateAt
    );

    @WebMethod(operationName = "GetFileContent", action = "http://iisda.government.bg/Competitons/IntegrationServices/ICompetitionService/GetFileContent")
    @Action(input = "http://iisda.government.bg/Competitons/IntegrationServices/ICompetitionService/GetFileContent", output = "http://iisda.government.bg/Competitons/IntegrationServices/ICompetitionService/GetFileContentResponse")
    @RequestWrapper(localName = "GetFileContent", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices", className = "indexbg.pjobs.wsclient.govcomp.GetFileContent")
    @ResponseWrapper(localName = "GetFileContentResponse", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices", className = "indexbg.pjobs.wsclient.govcomp.GetFileContentResponse")
    @WebResult(name = "GetFileContentResult", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
    public byte[] getFileContent(
        @WebParam(name = "fileID", targetNamespace = "http://iisda.government.bg/Competitons/IntegrationServices")
        java.lang.Long fileID
    );
}
